### ISSUE TITLE
Warning about googletest when configuring with cmake

### ISSUE THREAD

**Issue by lee30sonia** [msoeken/kitty#103]
I got this warning when calling cmake:

> CMake Warning at test/googletest/googletest/CMakeLists.txt:47 (project):
  VERSION keyword not followed by a value or was followed by a value that expanded to nothing.

It can still configure and compile successfully, so it's not a big problem I guess.

**Comment by msoeken** [comment]
In an existing repository run `git submodule update --recursive` after pulling the most recent changes.
